export type OpticalBounds = {
  left: number;
  top: number;
  right: number;
  bottom: number;
};

export const CONTENT_FIGURE_GAP_RATIO = 1 / 18;

export const contentFigureOpticalBounds = {
  "/images/presidential-crescendo-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-gorilla-goo-mini-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-grape-mini-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-nino-brown-moon-rocks-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-cherry-gelato-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-gorilla-goo-single-mini-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-daniel-larusso-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-orange-push-pop-mini-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-peach-mango-mini-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-garlic-cookie-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-peach-mango-mini-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-classic-mini-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-peach-mango-moon-rocks-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-galactic-gas-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-pink-cookie-single-mini-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-ghost-haze-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-pink-cookie-mini-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-skywalker-mini-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-pink-cookie-moon-rocks-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-laura-charles-moon-rocks-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-cap-junky-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-cherry-gelato-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-crescendo-mini-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-crescendo-mini-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-garlic-cookie-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-classic-single-mini-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-gorilla-goo-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-classic-mini-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-strawberry-mini-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-classic-moon-rocks-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-ghost-haze-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-x-series-single-mini-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-grape-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-skywalker-mini-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-watermelon-mini-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-skywalker-moon-rocks-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-gorilla-goo-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-skywalker-single-mini-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-laura-charles-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-strawberry-mini-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-strawberry-moon-rocks-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-grape-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-skywalker-single-mini-blunt-alternate-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-nino-brown-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-watermelon-mini-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-watermelon-moon-rocks-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-king-louis-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-waui-single-mini-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-opp-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-waui-mini-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-waui-moon-rocks-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-nyc-diesel-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-waui-single-mini-blunt-alternate-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-peach-mango-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-xj13-mini-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-whoa-si-whoa-moon-rocks-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-orange-push-pop-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-xxx-single-mini-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-pineapple-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-xxx-mini-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-xj13-moon-rocks-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-papaya-punch-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-pink-cookie-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-peach-mango-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-classic-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-pineapple-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-skywalker-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-pink-cookie-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-strawberry-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-classic-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-tropical-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-cherry-gelato-moon-rocks-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-daniel-larusso-moon-rocks-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-garlic-cookie-moon-rocks-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-blue-dream-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-cherry-gelato-mini-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-blue-raz-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-apricotti-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-blue-dream-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-blue-raz-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-cap-junky-mini-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-cherry-gelato-single-mini-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-cherry-mini-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-rainbow-belts-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-watermelon-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-sfv-og-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-ghost-haze-moon-rocks-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-gorilla-goo-moon-rocks-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-grape-moon-rocks-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-waui-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-skywalker-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-xj13-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-strawberry-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-xxx-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-tropical-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-xxx-blunt-alternate-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-watermelon-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-galactic-gas-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-waui-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-king-louis-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-xj13-infused-pre-roll-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-nyc-diesel-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-papaya-punch-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-rainbow-belts-blunt-packaging.webp": { left: 0, top: 0, right: 1, bottom: 1 },
  "/images/presidential-cherry-gelato-moon-rocks-menu-label.webp": { left: 0.089815, top: 0.065926, right: 0.908333, bottom: 0.92963 },
  "/images/presidential-blue-dream-infused-pre-roll-menu-label.webp": { left: 0.308333, top: 0.034074, right: 0.689815, bottom: 0.965185 },
  "/images/presidential-cap-junky-blunt-menu-label.webp": { left: 0.317593, top: 0.02, right: 0.681481, bottom: 0.964444 },
  "/images/presidential-gorilla-goo-mini-blunt-menu-label.webp": { left: 0.212963, top: 0.008889, right: 0.787037, bottom: 0.988148 },
  "/images/presidential-pink-cookies-mini-pre-roll-menu-label.webp": { left: 0.227778, top: 0.058519, right: 0.775926, bottom: 0.956296 },
  "/images/presidential-daniel-larusso-blunt-menu-label.webp": { left: 0.318519, top: 0.036296, right: 0.67963, bottom: 0.974815 },
  "/images/presidential-grape-mini-blunt-menu-label.webp": { left: 0.212963, top: 0.01037, right: 0.787037, bottom: 0.98963 },
  "/images/presidential-cherry-gelato-infused-pre-roll-menu-label.webp": { left: 0.308333, top: 0.034074, right: 0.689815, bottom: 0.965185 },
  "/images/presidential-skywalker-mini-pre-roll-menu-label.webp": { left: 0.232407, top: 0.048148, right: 0.780556, bottom: 0.945926 },
  "/images/presidential-gorilla-goo-moon-rocks-menu-label.webp": { left: 0.094444, top: 0.06963, right: 0.913889, bottom: 0.933333 },
  "/images/presidential-grape-moon-rocks-menu-label.webp": { left: 0.090741, top: 0.064444, right: 0.910185, bottom: 0.928889 },
  "/images/presidential-garlic-cookies-blunt-menu-label.webp": { left: 0.310185, top: 0.00963, right: 0.687963, bottom: 0.98963 },
  "/images/presidential-peach-mango-mini-blunt-menu-label.webp": { left: 0.212963, top: 0.01037, right: 0.787037, bottom: 0.98963 },
  "/images/presidential-strawberry-mini-pre-roll-menu-label.webp": { left: 0.225926, top: 0.042963, right: 0.774074, bottom: 0.940741 },
  "/images/presidential-galactic-gas-infused-pre-roll-menu-label.webp": { left: 0.308333, top: 0.043704, right: 0.689815, bottom: 0.975556 },
  "/images/presidential-peach-mango-moon-rocks-menu-label.webp": { left: 0.087963, top: 0.062222, right: 0.907407, bottom: 0.926667 },
  "/images/presidential-garlic-cookies-infused-pre-roll-menu-label.webp": { left: 0.296296, top: 0.02, right: 0.703704, bottom: 0.984444 },
  "/images/presidential-pink-cookies-mini-blunt-menu-label.webp": { left: 0.213889, top: 0.01037, right: 0.787963, bottom: 0.98963 },
  "/images/presidential-watermelon-mini-pre-roll-menu-label.webp": { left: 0.226852, top: 0.042222, right: 0.775, bottom: 0.940741 },
  "/images/presidential-laura-charles-blunt-menu-label.webp": { left: 0.313889, top: 0.020741, right: 0.684259, bottom: 0.986667 },
  "/images/presidential-pink-cookies-moon-rocks-menu-label.webp": { left: 0.089815, top: 0.067407, right: 0.908333, bottom: 0.931852 },
  "/images/presidential-ghost-train-haze-infused-pre-roll-menu-label.webp": { left: 0.300926, top: 0.02, right: 0.705556, bottom: 0.977778 },
  "/images/presidential-nino-brown-blunt-menu-label.webp": { left: 0.317593, top: 0.028148, right: 0.680556, bottom: 0.974074 },
  "/images/presidential-waui-mini-pre-roll-menu-label.webp": { left: 0.228704, top: 0.045926, right: 0.775926, bottom: 0.944444 },
  "/images/presidential-skywalker-mini-blunt-menu-label.webp": { left: 0.224074, top: 0.028148, right: 0.775926, bottom: 0.96963 },
  "/images/presidential-classic-moon-rocks-menu-label.webp": { left: 0.086111, top: 0.064444, right: 0.905556, bottom: 0.928889 },
  "/images/presidential-gorilla-goo-infused-pre-roll-menu-label.webp": { left: 0.318519, top: 0.060741, right: 0.67963, bottom: 0.938519 },
  "/images/presidential-orange-push-pop-blunt-menu-label.webp": { left: 0.315741, top: 0.022963, right: 0.682407, bottom: 0.976296 },
  "/images/presidential-watermelon-mini-blunt-menu-label.webp": { left: 0.211111, top: 0.01037, right: 0.785185, bottom: 0.988889 },
  "/images/presidential-cap-junky-mini-pre-roll-menu-label.webp": { left: 0.219444, top: 0.052593, right: 0.766667, bottom: 0.95037 },
  "/images/presidential-rainbow-belts-blunt-menu-label.webp": { left: 0.32037, top: 0.035556, right: 0.677778, bottom: 0.963704 },
  "/images/presidential-king-louis-infused-pre-roll-menu-label.webp": { left: 0.308333, top: 0.034074, right: 0.689815, bottom: 0.965185 },
  "/images/presidential-xj13-mini-blunt-menu-label.webp": { left: 0.221296, top: 0.025926, right: 0.777778, bottom: 0.972593 },
  "/images/presidential-cherry-gelato-mini-pre-roll-menu-label.webp": { left: 0.223148, top: 0.048889, right: 0.77037, bottom: 0.947407 },
  "/images/presidential-skywalker-moon-rocks-menu-label.webp": { left: 0.087963, top: 0.061481, right: 0.907407, bottom: 0.926667 },
  "/images/presidential-strawberry-moon-rocks-menu-label.webp": { left: 0.090741, top: 0.061481, right: 0.910185, bottom: 0.926667 },
  "/images/presidential-nyc-diesel-infused-pre-roll-menu-label.webp": { left: 0.308333, top: 0.034074, right: 0.689815, bottom: 0.965185 },
  "/images/presidential-blue-raspberry-mini-blunt-menu-label.webp": { left: 0.225926, top: 0.032593, right: 0.775926, bottom: 0.968889 },
  "/images/presidential-grape-mini-pre-roll-menu-label.webp": { left: 0.225926, top: 0.051111, right: 0.773148, bottom: 0.948889 },
  "/images/presidential-sfv-og-blunt-menu-label.webp": { left: 0.318519, top: 0.034074, right: 0.67963, bottom: 0.97037 },
  "/images/presidential-watermelon-moon-rocks-menu-label.webp": { left: 0.087037, top: 0.06963, right: 0.906481, bottom: 0.934074 },
  "/images/presidential-papaya-punch-infused-pre-roll-menu-label.webp": { left: 0.308333, top: 0.034074, right: 0.689815, bottom: 0.965185 },
  "/images/presidential-blue-raspberry-blunt-menu-label.webp": { left: 0.307407, top: 0, right: 0.691667, bottom: 0.999259 },
  "/images/presidential-classic-mini-pre-roll-menu-label.webp": { left: 0.225, top: 0.051111, right: 0.773148, bottom: 0.948148 },
  "/images/presidential-cherry-gelato-mini-blunt-menu-label.webp": { left: 0.208333, top: 0.007407, right: 0.783333, bottom: 0.986667 },
} as const satisfies Record<string, OpticalBounds>;

export function getContentFigureOpticalBounds(src: string): OpticalBounds {
  const bounds = (contentFigureOpticalBounds as Record<string, OpticalBounds>)[src];

  if (!bounds) {
    throw new Error("Missing optical bounds for content figure: " + src);
  }

  return bounds;
}
