const PRODUCT_SITE = "https://presidentialmoonrocks.com";

const PRODUCT_PATH_BY_PAGE_AND_FILENAME: Readonly<Record<string, string>> = {
  "/|presidential-crescendo-blunt-packaging.webp": "/moon-rocks/crescendo",
  "/|presidential-gorilla-goo-mini-blunt-packaging.webp": "/moon-rocks/gorilla-goo",
  "/|presidential-grape-mini-pre-roll-packaging.webp": "/moon-rocks/grape",
  "/|presidential-nino-brown-moon-rocks-packaging.webp": "/moon-rocks/presidential-line-nino-brown",
  "/|presidential-cherry-gelato-infused-pre-roll-packaging.webp": "/moon-rocks/cherry-gelato",
  "/|presidential-gorilla-goo-single-mini-blunt-packaging.webp": "/moon-rocks/gorilla-goo",
  "/|presidential-daniel-larusso-blunt-packaging.webp": "/moon-rocks/presidential-line-daniel-larusso",
  "/|presidential-orange-push-pop-mini-blunt-packaging.webp": "/moon-rocks/orange-push-pop",
  "/|presidential-peach-mango-mini-pre-roll-packaging.webp": "/moon-rocks/peach-mango",
  "/science|presidential-garlic-cookie-blunt-packaging.webp": "/moon-rocks/presidential-line-garlic-cookies",
  "/science|presidential-peach-mango-mini-blunt-packaging.webp": "/moon-rocks/peach-mango",
  "/science|presidential-classic-mini-pre-roll-packaging.webp": "/moon-rocks/presidential-prerolls",
  "/science|presidential-peach-mango-moon-rocks-packaging.webp": "/moon-rocks/peach-mango",
  "/science|presidential-galactic-gas-infused-pre-roll-packaging.webp": "/moon-rocks/galactic-gas",
  "/science/distillate|presidential-watermelon-mini-blunt-packaging.webp": "/moon-rocks/watermelon",
  "/science/distillate|presidential-watermelon-moon-rocks-packaging.webp": "/moon-rocks/watermelon",
  "/science/distillate|presidential-king-louis-infused-pre-roll-packaging.webp": "/moon-rocks/king-louis",
  "/science/live-resin|presidential-waui-single-mini-blunt-packaging.webp": "/moon-rocks/waui",
  "/science/live-resin|presidential-opp-blunt-packaging.webp": "/moon-rocks/orange-push-pop",
  "/science/live-resin|presidential-waui-mini-blunt-packaging.webp": "/moon-rocks/waui",
  "/science/live-rosin|presidential-waui-moon-rocks-packaging.webp": "/moon-rocks/waui",
  "/science/live-rosin|presidential-nyc-diesel-infused-pre-roll-packaging.webp": "/moon-rocks/nyc-diesel",
  "/science/live-rosin|presidential-waui-single-mini-blunt-alternate-packaging.webp": "/moon-rocks/waui",
  "/science/liquid-diamonds|presidential-peach-mango-blunt-packaging.webp": "/moon-rocks/peach-mango",
  "/science/liquid-diamonds|presidential-xj13-mini-blunt-packaging.webp": "/moon-rocks/xj-13",
  "/science/liquid-diamonds|presidential-whoa-si-whoa-moon-rocks-packaging.webp": "/moon-rocks/presidential-line-whoa-si-whoa",
  "/science/thca-vs-thc|presidential-classic-moon-rocks-packaging.webp": "/moon-rocks/presidential-moon-rocks",
  "/science/thca-vs-thc|presidential-ghost-haze-infused-pre-roll-packaging.webp": "/moon-rocks/presidential-line-ghost-haze-train",
  "/science/thca-vs-thc|presidential-x-series-single-mini-blunt-packaging.webp": "/moon-rocks/thc-design-blunts",
  "/science/decarboxylation|presidential-grape-blunt-packaging.webp": "/moon-rocks/grape",
  "/science/decarboxylation|presidential-skywalker-mini-blunt-packaging.webp": "/moon-rocks/skywalker",
  "/science/decarboxylation|presidential-watermelon-mini-pre-roll-packaging.webp": "/moon-rocks/watermelon",
  "/science/reading-a-lab-report|presidential-skywalker-moon-rocks-packaging.webp": "/moon-rocks/skywalker",
  "/science/reading-a-lab-report|presidential-gorilla-goo-infused-pre-roll-packaging.webp": "/moon-rocks/gorilla-goo",
  "/science/reading-a-lab-report|presidential-skywalker-single-mini-blunt-packaging.webp": "/moon-rocks/skywalker",
  "/science/terpenes|presidential-laura-charles-blunt-packaging.webp": "/moon-rocks/presidential-line-laura-charles",
  "/science/terpenes|presidential-strawberry-mini-blunt-packaging.webp": "/moon-rocks/strawberry",
  "/science/terpenes|presidential-strawberry-moon-rocks-packaging.webp": "/moon-rocks/strawberry",
  "/science/cannabinoids|presidential-grape-infused-pre-roll-packaging.webp": "/moon-rocks/grape",
  "/science/cannabinoids|presidential-skywalker-single-mini-blunt-alternate-packaging.webp": "/moon-rocks/skywalker",
  "/science/cannabinoids|presidential-nino-brown-blunt-packaging.webp": "/moon-rocks/presidential-line-nino-brown",
  "/infusion|presidential-pink-cookie-single-mini-blunt-packaging.webp": "/moon-rocks/pink-cookies",
  "/infusion|presidential-ghost-haze-blunt-packaging.webp": "/moon-rocks/presidential-line-ghost-haze-train",
  "/infusion|presidential-pink-cookie-mini-blunt-packaging.webp": "/moon-rocks/pink-cookies",
  "/infusion|presidential-skywalker-mini-pre-roll-packaging.webp": "/moon-rocks/skywalker",
  "/infusion|presidential-pink-cookie-moon-rocks-packaging.webp": "/moon-rocks/pink-cookies",
  "/infusion/how-infusion-works|presidential-orange-push-pop-infused-pre-roll-packaging.webp": "/moon-rocks/orange-push-pop",
  "/infusion/how-infusion-works|presidential-xxx-single-mini-blunt-packaging.webp": "/moon-rocks/xxx",
  "/infusion/how-infusion-works|presidential-pineapple-blunt-packaging.webp": "/moon-rocks/pineapple",
  "/infusion/surface-vs-saturation|presidential-xxx-mini-blunt-packaging.webp": "/moon-rocks/xxx",
  "/infusion/surface-vs-saturation|presidential-xj13-moon-rocks-packaging.webp": "/moon-rocks/xj-13",
  "/infusion/surface-vs-saturation|presidential-papaya-punch-infused-pre-roll-packaging.webp": "/moon-rocks/papaya-punch",
  "/infusion/kief-and-trichomes|presidential-pink-cookie-blunt-packaging.webp": "/moon-rocks/pink-cookies",
  "/infusion/kief-and-trichomes|presidential-peach-mango-infused-pre-roll-packaging.webp": "/moon-rocks/peach-mango",
  "/infusion/kief-and-trichomes|presidential-classic-blunt-packaging.webp": "/moon-rocks/presidential-blunts",
  "/infusion/why-infused-burns-differently|presidential-pineapple-infused-pre-roll-packaging.webp": "/moon-rocks/pineapple",
  "/infusion/why-infused-burns-differently|presidential-skywalker-blunt-packaging.webp": "/moon-rocks/skywalker",
  "/infusion/why-infused-burns-differently|presidential-pink-cookie-infused-pre-roll-packaging.webp": "/moon-rocks/pink-cookies",
  "/infusion/potency-by-format|presidential-strawberry-blunt-packaging.webp": "/moon-rocks/strawberry",
  "/infusion/potency-by-format|presidential-classic-infused-pre-roll-packaging.webp": "/moon-rocks/presidential-prerolls",
  "/infusion/potency-by-format|presidential-tropical-blunt-packaging.webp": "/moon-rocks/tropical",
  "/formats|presidential-laura-charles-moon-rocks-packaging.webp": "/moon-rocks/presidential-line-laura-charles",
  "/formats|presidential-cap-junky-infused-pre-roll-packaging.webp": "/moon-rocks/cap-junky",
  "/formats|presidential-cherry-gelato-blunt-packaging.webp": "/moon-rocks/cherry-gelato",
  "/formats|presidential-crescendo-mini-blunt-packaging.webp": "/moon-rocks/crescendo",
  "/formats|presidential-crescendo-mini-pre-roll-packaging.webp": "/moon-rocks/crescendo",
  "/formats/blunts|presidential-apricotti-blunt-packaging.webp": "/moon-rocks/presidential-line-apricotti",
  "/formats/blunts|presidential-blue-dream-blunt-packaging.webp": "/moon-rocks/blue-dream",
  "/formats/blunts|presidential-blue-raz-blunt-packaging.webp": "/moon-rocks/blue-raspberry",
  "/formats/mini-blunts|presidential-cap-junky-mini-blunt-packaging.webp": "/moon-rocks/cap-junky",
  "/formats/mini-blunts|presidential-cherry-gelato-single-mini-blunt-packaging.webp": "/moon-rocks/cherry-gelato",
  "/formats/mini-blunts|presidential-cherry-mini-blunt-packaging.webp": "/moon-rocks/cherry-gelato",
  "/formats/moon-rocks|presidential-cherry-gelato-moon-rocks-packaging.webp": "/moon-rocks/cherry-gelato",
  "/formats/moon-rocks|presidential-daniel-larusso-moon-rocks-packaging.webp": "/moon-rocks/presidential-line-daniel-larusso",
  "/formats/moon-rocks|presidential-garlic-cookie-moon-rocks-packaging.webp": "/moon-rocks/presidential-line-garlic-cookies",
  "/formats/infused-pre-rolls|presidential-blue-dream-infused-pre-roll-packaging.webp": "/moon-rocks/blue-dream",
  "/formats/infused-pre-rolls|presidential-cherry-gelato-mini-pre-roll-packaging.webp": "/moon-rocks/cherry-gelato",
  "/formats/infused-pre-rolls|presidential-blue-raz-infused-pre-roll-packaging.webp": "/moon-rocks/blue-raspberry",
  "/formats/vape-cartridges|presidential-rainbow-belts-infused-pre-roll-packaging.webp": "/moon-rocks/rainbow-belts",
  "/formats/vape-cartridges|presidential-watermelon-blunt-packaging.webp": "/moon-rocks/watermelon",
  "/formats/vape-cartridges|presidential-sfv-og-infused-pre-roll-packaging.webp": "/moon-rocks/sfv-og",
  "/guides|presidential-garlic-cookie-infused-pre-roll-packaging.webp": "/moon-rocks/presidential-line-garlic-cookies",
  "/guides|presidential-classic-single-mini-blunt-packaging.webp": "/moon-rocks/presidential-blunts",
  "/guides|presidential-gorilla-goo-blunt-packaging.webp": "/moon-rocks/gorilla-goo",
  "/guides|presidential-classic-mini-blunt-packaging.webp": "/moon-rocks/presidential-blunts",
  "/guides|presidential-strawberry-mini-pre-roll-packaging.webp": "/moon-rocks/strawberry",
  "/guides/how-to-smoke-moon-rocks|presidential-ghost-haze-moon-rocks-packaging.webp": "/moon-rocks/presidential-line-ghost-haze-train",
  "/guides/how-to-smoke-moon-rocks|presidential-gorilla-goo-moon-rocks-packaging.webp": "/moon-rocks/gorilla-goo",
  "/guides/how-to-smoke-moon-rocks|presidential-grape-moon-rocks-packaging.webp": "/moon-rocks/grape",
  "/guides/how-to-store-infused-cannabis|presidential-waui-blunt-packaging.webp": "/moon-rocks/waui",
  "/guides/how-to-store-infused-cannabis|presidential-skywalker-infused-pre-roll-packaging.webp": "/moon-rocks/skywalker",
  "/guides/how-to-store-infused-cannabis|presidential-xj13-blunt-packaging.webp": "/moon-rocks/xj-13",
  "/guides/temperature-guide|presidential-strawberry-infused-pre-roll-packaging.webp": "/moon-rocks/strawberry",
  "/guides/temperature-guide|presidential-xxx-blunt-packaging.webp": "/moon-rocks/xxx",
  "/guides/temperature-guide|presidential-tropical-infused-pre-roll-packaging.webp": "/moon-rocks/tropical",
  "/guides/what-to-look-for|presidential-xxx-blunt-alternate-packaging.webp": "/moon-rocks/xxx",
  "/guides/what-to-look-for|presidential-watermelon-infused-pre-roll-packaging.webp": "/moon-rocks/watermelon",
  "/guides/what-to-look-for|presidential-galactic-gas-blunt-packaging.webp": "/moon-rocks/galactic-gas",
  "/guides/beginners-guide|presidential-waui-infused-pre-roll-packaging.webp": "/moon-rocks/waui",
  "/guides/beginners-guide|presidential-king-louis-blunt-packaging.webp": "/moon-rocks/king-louis",
  "/guides/beginners-guide|presidential-xj13-infused-pre-roll-packaging.webp": "/moon-rocks/xj-13",
  "/about|presidential-nyc-diesel-blunt-packaging.webp": "/moon-rocks/nyc-diesel",
  "/about|presidential-papaya-punch-blunt-packaging.webp": "/moon-rocks/papaya-punch",
  "/about|presidential-rainbow-belts-blunt-packaging.webp": "/moon-rocks/rainbow-belts",
};

function filenameFromSource(source: string) {
  return source.split("/").pop() ?? source;
}

export function productHrefForImage(pagePath: string, imageSource: string) {
  const filename = filenameFromSource(imageSource);
  const productPath = PRODUCT_PATH_BY_PAGE_AND_FILENAME[`${pagePath}|${filename}`];

  return productPath ? `${PRODUCT_SITE}${productPath}` : undefined;
}
